name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package and docs deps
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mkdocs mkdocstrings mkdocstrings-python
      - name: Build docs
        run: |
          mkdocs build --strict
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force --clean


